### ISSUE TITLE
firebase認証部の作成

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-W/BombAttacker_Multi#4]
固有のuserIdでlobbyページ（マイページ？）に遷移
対戦ルームに入室したときにゲームが作られるように実装する。

**Comment by hirotada-t** [comment]
使用経験あるので作りますね。

**Comment by khkmgch** [comment]
ありがとうございます。お願いします。

今はfirebase実装していないので、
client/pages/index.tsxの
```
<Button variant="contained" component={Link} noLinkStyle href={`/lobby/${1}`}>
    Go to the Lobby
</Button>
```
部分で、href={`/lobby/${1}`}のようにuserId = 1のマイページに遷移するようになっています。

firebase実装後に、データベースからとってきたuserIdを使って、
href={`/lobby/${userId}`}に変更するとそれぞれのマイページに遷移できると思います。

**Comment by khkmgch** [comment]
↑
間違えました。

認証後にマイページ遷移なので、hrefで指定するのではなく、
タイトルページのuseEffect()内で、useRouter()を使って
push(`/lobby/${userId}`)で遷移させたほうがいいですね。
