### ISSUE TITLE
プレイヤーと敵の初期配置が被らないようにする

### ISSUE THREAD

**Issue by khkmgch** [Recursion-Group-W/BombAttacker_Multi#41]
プレイヤー ⇔ プレイヤー
プレイヤー ⇔ 敵

が、間隔を開けて配置されるようにしたい。

もしくは、プレイヤーが配置された後に
四方を壊せる障害物で囲む？

**Comment by hirotada-t** [comment]
@khkmgch 
これ終わってます？？

**Comment by khkmgch** [comment]
@hirotada-t 
終わりました！クローズします
