### ISSUE TITLE
node.jsとfirebaseのやり取りについて

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-W/BombAttacker_Multi#5]
@Hayato-Kossy @khkmgch 
当初、サーバーサイドの実装なしで、firebase ⇆reactで認証やデータの保存をすることを想定していましたが、
目標がリアルタイム対戦になり、サーバーにプレイヤーデータがあるので、nodejsとfirebase間でデータをやり取りするほうが良いかなと思ったんですが、どうでしょうか？
↓ ↓ ↓

react ⇆ firebase
google(orTwitter)アカウント認証(JWT発行)

nodejs ⇆ firebase
データ保存・取得（スコア、ランキングなど）

**Comment by hirotada-t** [comment]
今回の場合はfirebaseはフロント側から操作すれば十分かなと思ってます。

今考えているのは、
- ユーザー情報
- 過去の記録
- 累積の記録（ランキング）

くらいになると思います（もれがあれば指摘ください）。

これなら全てfirebaseに一任できるので、node側はゲームの処理に特化させれば良いかなと。

質問の例だと、
react ⇆ firebase
google(orTwitter)アカウント認証(JWT発行)・データ保存・取得（スコア、ランキングなど）
という感じです。
これならclient側にfirebase関連の記述が全てまとめられます。

**Comment by Hayato-Kossy** [comment]
僕もReact噛ませる必要性がないかなと思います。あとオンラインバトルタンクの流用の観点から見てもReactいらないかなと思いました。
昨日の進捗発表で他の人も言ってたんですが、仮に導入してもその合理的な理由を答えられない気がするって話になったので優先順位下げてもいいと思いました。Reactを導入してるチームもあったんですがその代わりPhaserを入れてなかったのでアニメーションで苦戦していました。

若干関係ないかもしれませんし、想定済みかもしれませんが、「ユーザー情報」に対して全員優先順位が並列なクライアントIDを持たせるだけではなくホストID的なものを持たせて「1番最初に部屋を作った人」を親にすると普通のオンライン対戦だけでなく個別ルームマッチの実装などもうまくいきそうな気がしました。

**Comment by hirotada-t** [comment]
今夜のMTG前に話せそうなら聞いておきたいですね。
聞いた内容はIssueにまとめておくので、Hayatoさんの都合が良い時に自習室にお願いします！

**Comment by Hayato-Kossy** [comment]
一応進捗報告会のIssueみたいの立てておきますね。また連絡するんですが14時くらいに自習室入ろうと思います。

**Comment by hirotada-t** [comment]
もう立てちゃいましたw
14時了解です！

**Comment by khkmgch** [comment]
@hirotada-t @Hayato-Kossy 

ホストID的なものを持たせて「1番最初に部屋を作った人」を親にすると普通のオンライン対戦だけでなく個別ルームマッチの実装など...

↑ ↑ ↑
の部分で、ホストは個別ルームに招待するリンクをツイートできるようにできたら良いですね。
