### ISSUE TITLE
各チームの進捗報告の内容

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-W/BombAttacker_Multi#6]
## 【MTG前】気になったこと・懸念点など

- なぜGCPを選ぶ？AWSは？
- Renderはラグが大きい（タンクの2人プレイでもたまにカクつく）→クラウドへの変更理由
- タンクと同じ構成ならデプロイ自体はRenderで実装済み
- GCPやAWSの学習コストが未知数
- AWSならUdemyで使用・UP経験あり（ただしバックエンドはPHP）
- ReactかVueのどちらを使うのか？という話か、どちらも使わないという話か

## 必要なタスク
- クライアント側の書き換え
- バックエンド側の書き換え
＝＝＝＝＝＝＝
- バックエンド/デプロイ環境の構築

**Comment by Hayato-Kossy** [comment]
重要なのはRenderは日本にサーバーがないのでオンラインゲームをする上でのレイテンシーが大丈夫なのかというところです。他のチームはgoogle cloudを使うらしいです。

**Comment by hirotada-t** [comment]
確かにバトルタンクはGoogleクラウド使っていますし、Renderにデプロイしたバトルタンクはラグがひどかったですね。
そちらもリサーチしておきます！
